[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "o6"
version = "1.0.0"
description = "Open-World Class Index"
authors = [{name="Tuomas Kontiainen", email="tuomas.Kontiainen@gmail.com"}]
readme = "README.md"
requires-python = ">=3.9"
license = {text = "Proprietary"}
dependencies = [
	
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 100
target-version = ['py39', 'py310', 'py311']

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false

[tool.ruff]
line-length = 100
target-version = "py39"
